### ISSUE TITLE
ERROS TRADUÇÃO EM PORTUGUÊS MIUI 14

### ISSUE THREAD

**Issue by NTK2845** [KcNirvana/MIUI-XML-14-PORTUGUESE#1]
Deixo várias fotos do sistema e uma das configurações Google onde existe erros, pois em vez de aparecer em português de Portugal aparece em inglês

![IMG_20221224_202036](https://user-images.githubusercontent.com/121359922/209450120-59f1f0e6-9c93-414b-949b-eabb193d99d4.jpg)
![IMG_20221224_202012](https://user-images.githubusercontent.com/121359922/209450121-c96c5430-1003-48c4-9ab3-51a578a79fc3.jpg)
![IMG_20221224_201954](https://user-images.githubusercontent.com/121359922/209450122-272c5f77-e488-4840-a3e5-4646951bc14f.jpg)

**Comment by KcNirvana** [comment]
Boas,
Obrigado pelo report.
Se detectares mais inglês ou brasileiro vai abrindo tickets.
Obrigado.

Grande abraço

**Comment by NTK2845** [comment]
Ok, feliz natal para ti e para os teus.
Abraço
