### ISSUE TITLE
ERROS TRADUÇÃO MIUI 14 ESTÁVEL 

### ISSUE THREAD

**Issue by NTK2845** [KcNirvana/MIUI-XML-14-PORTUGUESE#3]
Boas, deixo fotos das configurações de pagamento por NFC onde aparece em algumas opções em inglês.

Cumprimentos

![IMG_20221228_191421](https://user-images.githubusercontent.com/121359922/209861446-fd4ddd18-3709-4526-ab58-52d28f055238.jpg)
![IMG_20221228_191350](https://user-images.githubusercontent.com/121359922/209861450-9f0bf603-d525-4fc1-99df-393d240dbac5.jpg)
![IMG_20221228_191307](https://user-images.githubusercontent.com/121359922/209861452-77144056-ba50-4871-8e04-a46f2eb10ef2.jpg)

**Comment by KcNirvana** [comment]
Boas...
Mais uma vez muito obrigado pelos erros.
Grande abraço
