### ISSUE TITLE
Play store em inglês 

### ISSUE THREAD

**Issue by NTK2845** [KcNirvana/MIUI-XML-14-PORTUGUESE#6]
Boa tarde, a aba de pesquisar na play store não está em português e sim em inglês tal como mostro na foto.
Está situação é na Dev semanal.

Cumprimentos 
![Screenshot_2023-04-12-19-18-55-324_com android vending-edit](https://user-images.githubusercontent.com/121359922/231550149-6eb3c527-f583-4b42-8cd4-cf7dfb5aa6e3.jpg)

**Comment by KcNirvana** [comment]
Boas,
Obrigado pelo report mas não controlamos essa aplicação.
A PlayStore é traduzida diretamente pela Google.
Abraço
