### ISSUE TITLE
FALTA DE TRADUÇÃO EM VARIAS PARTES DO SISTEMA 

### ISSUE THREAD

**Issue by Cristiano2845** [KcNirvana/MIUI-XML-14-PORTUGUESE#7]
Boa tarde, venho indicar falta de tradução em algumas opções do sistema, e na central de controlo.
Na central de controlo são quase todas as opções que dá a mensagem em inglês em vez de português.
É a primeira versão Dev do Xiaomi 12
Deixo fotos em anexo
Cumprimentos 

![IMG_20231210_172914](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/d9189c1c-5feb-47be-87d6-a0ab3456a5a2)
![IMG_20231210_172849](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/9ed8b08d-4948-4216-8982-1f8f5d699cc1)
![IMG_20231210_172833](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/c7ad7782-2f2c-43f0-8a0b-eae9fd44309e)
![IMG_20231210_172817](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/cc78a967-ef05-49ae-92f0-236e2523e134)
![IMG_20231210_172751](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/2345f635-8197-4f45-ba94-7aa69b3af962)
![IMG_20231210_172711](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/22fc48e3-0f96-4095-b250-511c3f7b4267)
![IMG_20231210_172637](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/ae6a8fbf-d979-43a6-9aab-59c0d794ee99)
![IMG_20231210_172612](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/b4a63043-b86d-4d89-9f81-00999f38b5a8)
![IMG_20231210_172527](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/8636e7ff-ba57-4f92-9e65-11687749a868)

**Comment by Cristiano2845** [comment]
![Screenshot_2023-12-10-21-25-05-602_com miui freeform](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/cbba2d6c-4c29-4d0f-afa6-6d7c10b2aac0)
![Screenshot_2023-12-10-21-24-21-619_com miui securitycore](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/e56bf987-00af-4b64-a37c-560795ad5711)
![Screenshot_2023-12-10-21-24-08-985_com miui securitycore](https://github.com/KcNirvana/MIUI-XML-14-PORTUGUESE/assets/153451524/ed05951b-e605-414d-9ab1-495f2de5bbca)

**Comment by KcNirvana** [comment]
Boa tarde,
De que versão estamos a falar?
Miui14 ou HyperOS?

Obrigado.

Abraço

**Comment by Cristiano2845** [comment]
> Boa tarde, De que versão vamos falar? Miui14 ou HyperOS?
> 
> Obrigado.
> 
> Abraço

Boas, é da hyperos versão Dev Xiaomi 12

**Comment by KcNirvana** [comment]
Repositório errado.
Mas ok.
Vai ser corrigido para a próxima versão.
Obrigado.

Abraço

**Comment by Cristiano2845** [comment]
> Repositório errado. Mas tudo bem. Será corrigido para a próxima versão. Obrigado.
> 
> Abraço

Como assim repositório errado?

**Comment by KcNirvana** [comment]
Para HyperOS,
Este é o repositório certo:
https://github.com/KcNirvana/HyperOS-XML-1.0-Portuguese

Abraço

**Comment by Cristiano2845** [comment]
Quando se carrega para reportar bug na tradução na aba da ROM semanal manda para aqui não manda para o link que me mandaste

**Comment by Cristiano2845** [comment]
Já reportei no sítio certo

Abraço
